### PR TITLE
Smashing magazines structure

### PR DESCRIPTION
**Pull request by ghost**
-Added elements of the smashing magazines page.
-Used scales of grey to highlight articles.
-Used grid to position elements.
-Used google fonts to add styled font.
-Forms added.

### CODE REVIEW

**Comment by thsvr** [comment]
Project under review by Thaís Vieira (TSE)

**Comment by thsvr** [comment]
### **Status: CHANGES REQUIRED** :computer: :computer_mouse: 


Hi, @JohannRodriguez and @KossySteve your job looks amazing and you guys are almost there! :+1: You implemented almost everything and the project looks beautiful :fireworks: :fireworks: 

There are simple changes required listed below. Please do these adjustments and submit for the review again.

:v: As the original page, instead of 3 article on one row, you guys should put 2 articles in each of 2 rows. Can you please fix it? 

Original:
original

Clone:
student-print

:v:  Instead of using `<div>` as a parent element on lines 55, 97, 113, 165 on the HTML, it is better if you guys use `<section>` tags. And then replace the child `<section>` tags with other appropriate tags.  Please take a look at this link -> [HTML Semantic Elements - W3Schools](https://www.w3schools.com/html/html5_semantic_elements.asp) to check which tags can be more appropriate in your case.

After making these changes, please submit the project for another review.

### **Keep doing an amazing job** :computer: :computer:  **and good luck on the next review** :smile_cat: :smile_cat: 

### **Happy coding** :desktop_computer: :computer_mouse: 

If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo](url)

Thaís Vieira (TSE)

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi **Team**, great job 👍 We did great implementing the changes requested by the previous reviewer **congratulations**. We have now met the minimum requirements for the project to be approved 👌
 
Go ahead and merge to master and submit the project completion form
Good luck with your next projects 👨‍💻 
_Happy coding_
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

**Pull request merged**
